/** Full player-facing labels for item / set stats. */
export const STAT_DISPLAY_LABELS: Record<string, string> = {
  attack: "Damage",
  range: "Range",
  hp: "HP",
  mp: "MP",
  str: "Strength",
  int: "Intelligence",
  dex: "Dexterity",
  vit: "Vitality",
  for: "Fortitude",
  armor: "Armor",
  resistance: "Resistance",
  speed: "Speed",
  frequency: "A.Speed",
  crit: "Crit",
  critdamage: "Crit Damage",
  evasion: "Evasion",
  reflection: "Reflection",
  lifesteal: "Lifesteal",
  manasteal: "Manasteal",
  luck: "Luck",
  gold: "Gold",
  apiercing: "A.Piercing",
  rpiercing: "R.Piercing",
  courage: "Courage",
  mcourage: "M.Courage",
  pcourage: "P.Courage",
  stat: "Stat",
  xp: "XP",
  mp_cost: "Attack MP Cost",
  mp_reduction: "Skill MP Reduction",
  explosion: "Explosion",
  blast: "Blast",
  output: "Output",
  firesistance: "Fire resist",
  fzresistance: "Freeze resist",
  phresistance: "Physical resist",
  pnresistance: "Poison resist",
  stresistance: "Stun resist",
};
